# pnpm Workspace Configuration
# Defines which directories contain packages in this monorepo
# See: https://pnpm.io/workspaces

packages:
  # Published NPM packages
  - "packages/*"

  # Form.io packages (to be reorganized)
  - "formio"
  - "formio-core"
  - "formio-react"

  # Applications (not published)
  - "form-client-web-app"

  # Infrastructure (Terraform - no package.json)
  # - 'dss-formio-service'
